apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
    chart: {{ template "haskell-lang.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: {{ .Values.deployment.app }}
